<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Privacy Policy - Rs Handmade Fashion</title>
</head>
<body>
  <h1>Privacy Policy for Rs Handmade Fashion</h1>
  <p>
    Rs Handmade Fashion respects your privacy. We do not collect, store, or share your personal data through our Messenger bot.
  </p>
  <p>
    If you contact us through Messenger, we will only use your message to provide the best response and improve our services. We will not share your information with third parties.
  </p>
  <p>
    If you have any questions about our Privacy Policy, feel free to message our Facebook page.
  </p>
</body>
</html>
